/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package imsofa.kidscoding.gdbuilder.editors;

import org.fife.ui.rsyntaxtextarea.RSyntaxTextArea;
import org.fife.ui.rsyntaxtextarea.SyntaxConstants;
import org.fife.ui.rtextarea.RTextScrollPane;

/**
 *
 * @author lendle
 */
public class GDTextArea extends javax.swing.JPanel {

    /**
     * Creates new form GDTextArea
     */
    public GDTextArea() {
        initComponents();
        ((RSyntaxTextArea)this.code).setSyntaxEditingStyle(SyntaxConstants.SYNTAX_STYLE_PYTHON);
        ((RSyntaxTextArea)this.code).setAutoIndentEnabled(true);
        ((RTextScrollPane)jScrollPane1).setLineNumbersEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new RTextScrollPane((RSyntaxTextArea)code);
        code = new RSyntaxTextArea();

        setLayout(new java.awt.BorderLayout());

        code.setColumns(20);
        code.setRows(5);
        jScrollPane1.setViewportView(code);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea code;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
