/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package imsofa.kidscoding.gdbuilder.editors;

import java.io.File;
import java.io.IOException;
import org.apache.commons.io.FileUtils;
import org.fife.ui.rsyntaxtextarea.RSyntaxTextArea;
import org.fife.ui.rsyntaxtextarea.SyntaxConstants;
import org.fife.ui.rtextarea.RTextScrollPane;

/**
 *
 * @author lendle
 */
public class GDTextArea extends javax.swing.JPanel implements GDFileEditor{
    private boolean modified=false;
    /**
     * Creates new form GDTextArea
     */
    public GDTextArea() {
        initComponents();
        ((RSyntaxTextArea)this.code).setSyntaxEditingStyle(SyntaxConstants.SYNTAX_STYLE_PYTHON);
        ((RSyntaxTextArea)this.code).setAutoIndentEnabled(true);
        ((RTextScrollPane)jScrollPane1).setLineNumbersEnabled(true);
    }
    
    public String getCode(){
        return this.code.getText();
    }
    
    public void setCode(String code){
        this.code.setText(code);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new RTextScrollPane((RSyntaxTextArea)code);
        code = new RSyntaxTextArea();

        setLayout(new java.awt.BorderLayout());

        code.setColumns(20);
        code.setRows(5);
        code.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                codePropertyChange(evt);
            }
        });
        jScrollPane1.setViewportView(code);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void codePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_codePropertyChange
        // TODO add your handling code here:
        if(evt.getPropertyName().equals("text")){
            modified=true;
        }
    }//GEN-LAST:event_codePropertyChange


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea code;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void init(File gdFile) {
        try {
            String code=FileUtils.readFileToString(gdFile, "utf-8");
            this.setCode(code);
            modified=false;
        } catch (IOException ex) {
            ex.printStackTrace();
        }
    }

    @Override
    public boolean isModified() {
        return modified;
    }
}
