/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package imsofa.kidscoding.gdbuilder.editors;

/**
 *
 * @author lendle
 */
public class GridEditor extends javax.swing.JPanel {
    private GridModel gridModel=new GridModel();
    /**
     * Creates new form GridEditor
     */
    public GridEditor() {
        initComponents();
        this.propsTable.setModel(new GridEditorTableModel(gridModel));
        this.propsTable.getColumnModel().getColumn(1).setCellEditor(new GridEditorTableCellEditor());
        this.propsTable.getColumnModel().getColumn(1).setCellRenderer(new GridEditorTableCellRenderer());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        propsTable = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        propsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        propsTable.setRowHeight(25);
        jScrollPane1.setViewportView(propsTable);

        jTabbedPane1.addTab("Properties", jScrollPane1);

        add(jTabbedPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable propsTable;
    // End of variables declaration//GEN-END:variables
}
