/* Generated By:JavaCC: Do not edit this line. GDParserConstants.java */
package imsofa.kidscoding.gdbuilder;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface GDParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int VAR_MODIFIER = 3;
  /** RegularExpression Id. */
  int FUNC = 4;
  /** RegularExpression Id. */
  int COLON = 5;
  /** RegularExpression Id. */
  int CODE_LINE = 6;
  /** RegularExpression Id. */
  int CODE_LINE_END = 7;
  /** RegularExpression Id. */
  int NEXT_FUNC = 8;
  /** RegularExpression Id. */
  int NEXT_VAR = 9;
  /** RegularExpression Id. */
  int ID = 10;
  /** RegularExpression Id. */
  int DECIMAL_LITERAL = 11;
  /** RegularExpression Id. */
  int EXPONENT = 12;
  /** RegularExpression Id. */
  int FLOATING_POINT_LITERAL = 13;
  /** RegularExpression Id. */
  int STRING_LITERAL = 14;
  /** RegularExpression Id. */
  int LEFT_PARENTHESES = 15;
  /** RegularExpression Id. */
  int RIGHT_PARENTHESES = 16;
  /** RegularExpression Id. */
  int COMMA = 17;
  /** RegularExpression Id. */
  int ASSIGN = 18;
  /** RegularExpression Id. */
  int NEWLINE = 19;

  /** Lexical state. */
  int FUNCTION_BODY = 0;
  /** Lexical state. */
  int FUNCTION_DECLARATION = 1;
  /** Lexical state. */
  int DEFAULT = 2;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\f\"",
    "<VAR_MODIFIER>",
    "\"func\"",
    "<COLON>",
    "<CODE_LINE>",
    "<CODE_LINE_END>",
    "\"func\"",
    "<NEXT_VAR>",
    "<ID>",
    "<DECIMAL_LITERAL>",
    "<EXPONENT>",
    "<FLOATING_POINT_LITERAL>",
    "<STRING_LITERAL>",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\"=\"",
    "<NEWLINE>",
  };

}
