/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package imsofa.kidscoding.gdbuilder;

import imsofa.kidscoding.gdbuilder.editors.GDFileEditor;
import imsofa.kidscoding.gdbuilder.editors.GDFileEditorFactory;
import java.io.File;
import java.io.IOException;
import javax.swing.JComponent;
import javax.swing.SwingUtilities;

/**
 *
 * @author lendle
 */
public class Main extends javax.swing.JFrame {

    private File editingFile = null;

    /**
     * Creates new form NewJFrame
     */
    public Main() {
        initComponents();
        this.setSize(1024, 600);
        FileTreeModel model = new FileTreeModel(new File("godot"));
        this.contentTree.setModel(model);
        this.contentTree.setCellRenderer(new FileTreeCellRenderer());
        this.contentTree.updateUI();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        contentTree = new javax.swing.JTree();
        editorContainer = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitPane1.setDividerLocation(300);

        contentTree.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                contentTreeMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(contentTree);

        jSplitPane1.setLeftComponent(jScrollPane2);

        editorContainer.setLayout(new java.awt.BorderLayout());
        jSplitPane1.setRightComponent(editorContainer);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void contentTreeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contentTreeMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {
            try {
                File file = (File) contentTree.getSelectionPath().getLastPathComponent();
                if (editorContainer.getComponentCount() != 0) {
                    editorContainer.removeAll();
                }

                if (file.getName().endsWith(".gd")) {
                    GDFileEditor editor = GDFileEditorFactory.getEditor(file);
                    editor.init(file);
                    editorContainer.add((JComponent) editor);
                    SwingUtilities.invokeLater(new Runnable() {
                        @Override
                        public void run() {
                            editorContainer.revalidate();
                            editorContainer.repaint();
                        }
                    });
                }
            } catch (IOException ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_contentTreeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTree contentTree;
    private javax.swing.JPanel editorContainer;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
}
